### ISSUE TITLE
maskrcnn-benchmark vs. Detectron2

### ISSUE THREAD

**Issue by SkalskiP** [amazon-research/siam-mot#12]
I have a question rather than an issue. Why did you choose to use [maskrcnn-benchmark](https://github.com/facebookresearch/maskrcnn-benchmark), which is no longer actively supported? Do you think SiamMOT could use [Detectron2](https://github.com/facebookresearch/detectron2) instead? If so, could you give me some tips on how to do this?

**Comment by bingshuai2019** [comment]
There is no particular technique reason that we prefer maskrcnn-benchmark over Detectron2. The codes can be easily refactored to be within Detectron2 infrastructure.  

If you've already dealt with Detectron2 before, you just need to follow the standard training scripts in Detectron2 to do the refactor of model training.

One thing to be aware is that the __get_item__ function in the dataset class needs to be refactored accordingly (e.g. returned value and the data structure of the bounding box in an image, etc.)

I'm happy to chat more if you have more specific questions for code refactor.

**Comment by SkalskiP** [comment]
Hi @bingshuai2019 sounds like a pretty interesting free-time project. I see that you published your code under Apache-2.0 License. In fact, I would be willing to build an alternative version of the SiamMot just based on the Detectron2. I'd also be happy to talk about how to do it, I'll probably need some time to read through the paper and the published code. But then if you could find the time I'd be happy to talk. :)

**Comment by fanq15** [comment]
@SkalskiP Hi, did you build the detectron2 version of SiamMot?
