### ISSUE TITLE
ffmpeg

### ISSUE THREAD

**Issue by yanghaibin-cool** [amazon-research/siam-mot#27]
when I run demo.py,I meet the problem which ffmpeg._run.Error: ffprobe error (see stderr output for detail).How can I solve it,thank you.

**Comment by mondrasovic** [comment]
Hello.

I experienced the very same error on my local machine as well as Google Colab. What you need to do is simply **re-install** the `ffmpeg-python` package. I have this ugly hack programmed in my Jupyter notebook pipeline. 

If there is a better solution or an explanation for why this happens, I would be happy to read about it.

Here are the commands:

```
pip uninstall -y ffmpeg-python
pip install ffmpeg-python
```

Hope this helps.

**Comment by yanghaibin-cool** [comment]
> Hello.
> 
> I experienced the very same error on my local machine as well as Google Colab. What you need to do is simply **re-install** the `ffmpeg-python` package. I have this ugly hack programmed in my Jupyter notebook pipeline.
> 
> If there is a better solution or an explanation for why this happens, I would be happy to read about it.
> 
> Here are the commands:
> 
> ```
> pip uninstall -y ffmpeg-python
> pip install ffmpeg-python
> ```
> 
> Hope this helps.

Thank you very much.It works.
