### ISSUE TITLE
errors about train_net.py

### ISSUE THREAD

**Issue by yanghaibin-cool** [amazon-research/siam-mot#29]
This is my train.py parameter configuration:
![图片](https://user-images.githubusercontent.com/72022193/132948825-eed2b84f-38ee-4844-81e3-3e840a2a0592.png)
This is my data structure：
![图片](https://user-images.githubusercontent.com/72022193/132948897-abaf882f-7961-4b44-9af0-5459de74551c.png)
But I have this problem：
![图片](https://user-images.githubusercontent.com/72022193/132948931-97c19267-6779-463d-aafe-be23100287ac.png)
I think there's something wrong here.But I do not know how to solve, ask for help, thank you
![图片](https://user-images.githubusercontent.com/72022193/132948996-14e27f64-8054-4e1b-8237-8a400080690d.png)
![图片](https://user-images.githubusercontent.com/72022193/132949011-d7af049f-3d7c-41f0-a673-a926e2012bda.png)

**Comment by yanghaibin-cool** [comment]
I modified this place, but I still encountered errors：
![图片](https://user-images.githubusercontent.com/72022193/132949389-0980ac73-0d86-4848-9b75-d093e12add24.png)
Ask for help online，thank you.

**Comment by mondrasovic** [comment]
> I modified this place, but I still encountered errors：
> ![图片](https://user-images.githubusercontent.com/72022193/132949389-0980ac73-0d86-4848-9b75-d093e12add24.png)
> ![图片](https://user-images.githubusercontent.com/72022193/132949449-af0a22f0-f94f-4ffc-93b4-fe3502f14ef5.png)
> Ask for help online，thank you.

The error message practically tells you a lot about the solution. There's a **type mismatch**. The `DATASETS.TRAIN` key needs to be a `tuple`, not a `string`. You have to make it a single element tuple, thus:

```
...
TRAIN: ("MOT17",)
...
```

Notice the **additional comma** after the `MOT17` string. That's what you are missing right now.

**Comment by yanghaibin-cool** [comment]
Thank you so much for helping me so many times.My goal was to train the model on MOT17.Then I have made some modifications to what you said：
DLA_34_FPN_EMM_MOT17.yaml:
![图片](https://user-images.githubusercontent.com/72022193/132982343-a8029007-428f-47b2-aa75-fda82c533a2f.png)
train_net.py:
![图片](https://user-images.githubusercontent.com/72022193/132982376-7f9d9fa4-0a4e-4645-85e9-3396aa3852f8.png)
Then I ran into the following problem：
![图片](https://user-images.githubusercontent.com/72022193/132982448-efa3464b-1ab9-46ce-868a-2ac273d081ca.png)
Excuse me, what is the reason.Thank you.




> > I modified this place, but I still encountered errors：
> > ![图片](https://user-images.githubusercontent.com/72022193/132949389-0980ac73-0d86-4848-9b75-d093e12add24.png)
> > ![图片](https://user-images.githubusercontent.com/72022193/132949449-af0a22f0-f94f-4ffc-93b4-fe3502f14ef5.png)
> > Ask for help online，thank you.
> 
> The error message practically tells you a lot about the solution. There's a **type mismatch**. The `DATASETS.TRAIN` key needs to be a `tuple`, not a `string`. You have to make it a single element tuple, thus:
> 
> ```
> ...
>   TRAIN: ("MOT17",)
> ...
> ```
> 
> Notice the **additional comma** after the `MOT17` string. That's what you are missing right now.
