### ISSUE TITLE
Add tracker to our own detector

### ISSUE THREAD

**Issue by AtGrover** [amazon-research/siam-mot#5]
Is there a way to add this tracker to our own detector?

**Comment by GrantorShadow** [comment]
Can you maybe describe in detail what do you wish to do? like I have some idea what you're talking about but not sure..

**Comment by bingshuai2019** [comment]
Not sure what exactly do you mean, basically the current inference allows the tracker to use its own detection. Refer to issue #7 for details.

**Comment by AtGrover** [comment]
Thank you, apologies for my ambiguous wording. 
#7 was the same issue that I wanted to know
