### ISSUE TITLE
Weights not available

### ISSUE THREAD

**Issue by GrantorShadow** [amazon-research/siam-mot#6]
Dear authors,
Thanks for making your code available, I am grateful to you for it.
In regards to the code base, I was wondering when would the weights for the MOTChallenge-2017 Test (Public detection) data set, as referenced in the model zoo readme be available? 

Thanks again.

**Comment by bingshuai2019** [comment]
Hi, Thanks for your interest.

We will gradually release the model weights here: https://github.com/amazon-research/siam-mot/blob/main/readme/model_zoo.md#motchallenge-2017-test-public-detection

Currently, we only release the model trained on CrowdHuman, please stay tuned for more model weights very soon.

**Comment by GrantorShadow** [comment]
Thank you !
