### ISSUE TITLE
only use tracker

### ISSUE THREAD

**Issue by dyh-bupt** [amazon-research/siam-mot#7]
Hi, excellent work! But I have some questions.
If I already have bboxes in the video and I only want to use the SiamMOT for tracking-by-detection, what should I do.
Particularly, how to just inference with my bboxes. And, how to train SiamMOT with my bboxes and then inference.
Thank you. 
(maybe issue #5 is the same problem with me)

**Comment by bingshuai2019** [comment]
Yeah, the tracker allows to use public detection by setting INFERENCE.USE_GIVEN_DETECTIONS to be True, but there is some caveat to that. We will release how to do that in the next update (within 1 day.)

**Comment by dyh-bupt** [comment]
thanks for your reply.
I've run the tracker with INFERENCE.USE_GIVEN_DETECTIONS=True.
But I found that the output tracks'bboxes are not exactly same with the public detections.
So the SiamMOT has fixed the input bboxes? How does it do that ?
What should I do if I just want to use the public detections and don't want the tracker to fix them?
thank you~  ^.^

**Comment by bingshuai2019** [comment]
The code that adjusts the public detection can be found here: https://github.com/amazon-research/siam-mot/blob/main/siammot/modelling/roi_heads.py#L28-L32

In order to use the public detection as is, you can change the codes accordingly (e.g. use the codes within else statement in the above code) .
